### ISSUE TITLE
Can't download the Nik Chromium dev sync version of Chromium

### ISSUE THREAD

**Issue by CypherNL** [mkorthof/chrupd#1]
When i edit the cmd file to change the stable nosync version to dev sync version or i use the proper arguments it outputs this:

> 2018-07-17 16:39:40 Start (pid:8028 name:powershell scheduler:0)
> 2018-07-17 16:39:40 Forcing update, ignoring current version 
> 2018-07-17 16:39:40 Checksite: "chromium.woolyss.com", Editor: "Nik", Channel: "dev"
> 2018-07-17 16:39:41 No matching versions found

The feed does contain the dev sync build (https://chromium.woolyss.com/feed/windows-64-bit) so the feed might be changed.

**Comment by mkorthof** [comment]
Looks like a mismatch between the version and filename in the RSS:

> 2) Development version:
> Editor: Nik
> Architecture: 64-bit
> Channel: dev
> Version: **68.0.3424.0**
> Revision: **556419**

https://github.com/henrypp/chromium/releases/download/v69.0.3496.0-r576176-win64/chromium-sync.exe
