### ISSUE TITLE
Problem Installing Ungoogled Chromium

### ISSUE THREAD

**Issue by vrnge** [mkorthof/chrupd#12]
I ran this command:

> .\chrupd.cmd -editor Ungoogled -channel stable -arch 64bit

I got this output:

> Simple Chromium Updater ( chrupd.cmd 20210109 )                                                                        
> OS Detected: "Windows 10" (10.0, Workstation)
> Task Scheduler Mode: 1 "Normal"
> Logging to: "C:\Users\...\Downloads\chrupd-master\chrupd-master\chrupd.log"
> WARNING: Could not find Chromium, initial installation will be done by the downloaded installer...
> Using the following settings:
> Feed "chromium.woolyss.com" name "Ungoogled" editor "Marmaduke" architecture "64-bit" channel "stable"
> 
> New Chromium version "87.0.4280.141" from 2021-01-14 is available (6 days ago)
> Downloading "https://github.com/macchrome/winchrome/releases/download/v87.0.4280.141-r812852-Win64/ungoogled-chromium-87.0.4280.141-1_Win64.7z"
> Saving as: "C:\Users\...\AppData\Local\Temp\ungoogled-chromium-"

Then it quit. Ungoogled Chromium is not installed.

Thanks for your help!

**Comment by mkorthof** [comment]
Should be fixed in latest version
