### ISSUE TITLE
Issues with parameter "-crTask"

### ISSUE THREAD

**Issue by engelhro** [mkorthof/chrupd#15]
Hello,

I'm not sure how to correctly use `chrupd` in combination with the `-crTask` parameter:

1. Adding the parameter to the command line apparently results in *only* the update task being created, but not the installation itself taking place?

	This is not clearly mentioned in the readme, and the help output with the *optional* parameter (showing a `[-crTask]` part) seems to imply that the installation always takes place **and** the update task creation is just an optional addition.

2. If the parameter only creates the task itself, are the other parameters still needed for the task to "know" which update check needs to take place? Or does it look at a possible existing installation and updates this variant?

3. If the answer to the question from item 2. above (are further parameters required?) is "no", why does the script not complain about the then unnecessary (and possibly ignored) additional parameters?

	 And vice versa: if the answer is "yes", the question is why does the script not complain about missing parameters and also runs with a standalone `chrupd -crTask` call? Does an existing chromium installation get overwritten with the default (Hibbiki stable) in this case?

Thanks for clarifying the use of the `-crTask` parameter in both the readme and also the script output (=help)!

**Comment by mkorthof** [comment]
There is no "install" as such, arguments are optional and use defaults if missing (they can also be set inside script).
In whichever way the options are given -- crTask will use them to create the task, using the path where the script is.

**Comment by engelhro** [comment]
> There is no "install" as such

Okay. It's a a download followed by an extraction step. Doesn't address the questions I had.

> arguments are optional and use defaults if missing (they can also be set inside script).

This still leaves open all questions I had: what if the defaults (or values set in the script) contradict an existing "installation"?

> In whichever way the options are given `-crTask` will use them to create the task, using the path where the script is.

I assume this is the answer? Any previous call to `chrupd` (and any "installation" performed by it) and its parameters get ignored by the task which runs the next day (with possibly deviating settings)? So I might end up with two different browsers if I or other users inadvertently use different parameters (or forget to set them on the additional script execution for the task creation), right?

I think this behavior should be stated more clearly in the readme.
