### ISSUE TITLE
Invalid parameter (Task Scheduler)

### ISSUE THREAD

**Issue by yani** [mkorthof/chrupd#16]
I had an older version of chrupd but deleted the task from scheduler, removed all older files, put the new version in the original directory and ran `-crTask` again.

Parameters that were added to the scheduled task:
```
C:\chrupd\chrupd.vbs -scheduler -editor Hibbiki -arch 64-bit -channel stable -cAutoUp
```

`-cAutoUp` seems to be an invalid parameter and fails to start the update process. After removing this parameter the update process worked again.

Also, I checked the .vbs file that was created. The path was `C:\chrupdchrupd.vbs` which should have been `C:\\chrupd\\chrupd.vbs`

Current version: **20210122**

**Comment by mkorthof** [comment]
Thanks. Indeed there were 2 characters missing :)
A `'\'` in the vbs content and `$AutoUp` instead of `$cAutoUp` in the task args.

Fixed in latest commit
