### ISSUE TITLE
Ungoogled Chromium - Creates folder for each update on desktop

### ISSUE THREAD

**Issue by brokoler** [mkorthof/chrupd#18]
**Issue**
Installing Ungoogled Chromium behaves different from other editor versions. Ungoogled is extracted on the desktop, which results in a folder on the desktop for each update.

**Following command was used**
".\chrupd.cmd -editor Ungoogled -arch 64bit -channel stable"

**Recommended solution**
Install following release instead of the archived 7z:
https://github.com/macchrome/winchrome/releases/download/v92.0.4515.107-r885287-Win64/92.0.4515.107_ungoogled_mini_installer.exe
Behavior should be identical to Marmaduke then

**Comment by mkorthof** [comment]
Done, script should autoupdate
