### ISSUE TITLE
[Feature Request] Add an option to install for all users

### ISSUE THREAD

**Issue by dragani** [mkorthof/chrupd#20]
Thanks for the script! Would it be possible for you to add an option to run the Chromium installer with --system-level argument so that the browser gets installed under Program Files folder instead of current user profile?

**Comment by tomtheone** [comment]
Have the same need here.

**Comment by mkorthof** [comment]
I think that should be as simple as adding ` --system-level` here:
https://github.com/mkorthof/chrupd/blob/4f1541c702e7f980a6446b1a5b4a78303b3f664d/chrupd.cmd#L1917

I'll see if I can test this one of these days and add a proper option for it.

**Comment by mkorthof** [comment]
https://github.com/mkorthof/chrupd/commit/c0d0cd49e6a53ca0e3bce5fd7a02f7e6490bf77d added `-sysLvl`, see `chrupd -advhelp`
(untested)

Script should auto update.
