### ISSUE TITLE
[Feature request] Add eloston Ungoogled Chromium build

### ISSUE THREAD

**Issue by brokoler** [mkorthof/chrupd#21]
Hello,

right now only the Marmaduke build of Ungoogled Chromium is supported.

Would it be possible to also add the official eloston build with a new editor string?
https://github.com/ungoogled-software/ungoogled-chromium

It is more feature complete (supports more flags), would be great to choose the build

Pre-compiled builds can be found here: https://github.com/ungoogled-software/ungoogled-chromium-windows

**Comment by mkorthof** [comment]
Hi,

Looks like these builds are not included in [woolyss](https://chromium.woolyss.com/) api and RSS feed (only the binaries are listed), so chrupd does not find them. Older versions of chrupd included a json parser for github which would probably work..

**Comment by mkorthof** [comment]
Found and put back the code. Tbh I'm not sure how useful this is since it seems Eloston-UngoogledChromium repo does not include much info for chrupd to work with (e.g. file hash). You'll have to use `-ignHash`  option.

I'll wrap up and post a test version here soon.

```
PS C:\> [ gh-json *% > ] .\chrupd.ps1 -debug 0 -editor Eloston-UngoogledChromium -channel dev -cAutoUp 0 -ignHash
 Simple Chromium Updater ( chrupd.ps1 20220709 )

OS Detected: "Windows 10" (10.0, Workstation)
Task Scheduler Mode: 1 "Normal"
Logging to: "C:\chrupd.log"

Currently installed Chromium version: "105.0.5155.0"

Using the following settings:
Feed "github.com" title "Eloston-UngoogledChromium" editor "github-actions[bot]" architecture "64-bit" channel "dev"


(!) Ignoring hash. Could not verify checksum of installer/archive.
    Press any key to abort or "c" to continue...

    Waiting 30 seconds before continuing, 29s left

New Chromium version "103.0.5060.53-1.1" from 2022-06-24 is available (15 days ago)
Downloading "https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/103.0.5060.53-1.1/ungoogled-chromium_103.0.5060.53-1.1_installer_x64.exe"
Saving as: "C:\Users\User\AppData\Local\Temp\ungoogled-chromium_103.0.5060.53-1.1_installer_x64.exe"
Ignoring hash, using hash from downloaded installer: "023F4DB8167BFABBB87FFC003EAD3AA2CA90B525"
SHA1 hash matches "023F4DB8167BFABBB87FFC003EAD3AA2CA90B525"
Executing "ungoogled-chromium_..."
```
