### ISSUE TITLE
[Feature Request] Add @RobRich999 build back

### ISSUE THREAD

**Issue by JustnotJustin** [mkorthof/chrupd#29]
It was removed but since the project is active, it would be nice to have it back. It's on Woolyss' website.

**Comment by user340q** [comment]
Hi, my PC doesn't support avx2 so I'm trying to find a way to install the win64-avx RobRich build via chrupd.  I can't seem to get it to pull that branch instead of win64-avx2. Is this possible with chrupd as-is? Thank you!
