### ISSUE TITLE
'-linkArgs' does not work.

### ISSUE THREAD

**Issue by 911432** [mkorthof/chrupd#32]
I use .\chrupd.cmd -linkArgs "-incognite"
However, no options are added to the desktop link.
![1234](https://github.com/mkorthof/chrupd/assets/30204381/8b4928ae-303a-45cc-acf2-63c3ef6acb4b)

**Comment by mkorthof** [comment]
This option only works with [Archive Installs](https://github.com/mkorthof/chrupd/blob/master/docs/Options.md#archive-installs), for releases that come as [Archive Files](https://github.com/mkorthof/chrupd/blob/master/docs/Files.md#archives).

**Comment by 911432** [comment]
How do I install the archive file?

**Comment by 911432** [comment]
How do I install the archive file?
```
chrimd.cmd ???
```

**Comment by 911432** [comment]
How do I install the archive file?
```
chrupd.cmd ???
```
