### ISSUE TITLE
[Feature Request] Add WinRAR support

### ISSUE THREAD

**Issue by brokoler** [mkorthof/chrupd#6]
Hello,

thanks a lot for you script. It would be great if WinRAR support could be added besides 7-Zip, which allows the user to choose between both programs. In my case, only WinRAR was installed and I got an error when running the script. 7-Zip was needed, but I don't have any use for this program.

**Comment by mkorthof** [comment]
**2020-12-02** auto download 7zip if missing
https://github.com/mkorthof/chrupd/blob/master/CHANGES.md#changes
