### ISSUE TITLE
Update script fails to detect sha1/md5 checksums in RSS feed

### ISSUE THREAD

**Issue by artello73** [mkorthof/chrupd#8]
Looks like RSS feed structure has changed, script failing with the message below:

Simple Chromium Updater (chrupd.cmd)
------------------------------------

OS Detected: "Windows 10" (10.0, Workstation)
Task Scheduler Mode: 1, Normal

Logging to: "C:\chrupd\\chrupd.log"

Currently installed Chromium version: "83.0.4103.61"

Using the folowing settings:
Checking: "chromium.woolyss.com", Editor: "Hibbiki", Architecture: "64-bit", Channel: "stable"

ERROR: No valid hash for installer/archive file found, exiting...

**Comment by mkorthof** [comment]
Hi @artello73 

Thanks for noticing, looks like it indeed changed since the 16th. I'll change the script accordingly.
